### PR TITLE
Add module-level docs for ergo.metaculus 

### PR DESCRIPTION
**Pull request by wbaizer**
to be able to do this in a nice way, also start reading env variables from a .env file

EVERYONE WILL NEED TO ADD THE .env FILE ONCE THIS IS MERGED

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
:white_check_mark: A review job has been created and sent to the PullRequest network.  
*****  
Check the status or cancel PullRequest code review [here](https://will-fe7b.pullrequest.tech/dash/projects/1/wbaizer/ought-copy/reviews).

**Comment by wbaizer** [comment]
We need to find a better solution than providing username and password in the code. Maybe read it from an environment variable and set up Travis to provide that environment variable.

**Comment by wbaizer** [comment]
@ stuhlmueller I:
1. Removed username and password
2. expanded the explanation of the module-level example for metaculus.py
3. Created a notebook for examples from the documentation and linked to it from the index page of the documentation

Merge if you feel like it's ready

**Comment by wbaizer** [comment]
Goal for [doctests](http://doc.pytest.org/en/latest/doctest.html) is to run, so a valid username/password is needed?

Would prefer not having the code from docs copied in a notebook. Could get out of sync, feels redundant.

**Pull request merged**
